title: "ACUVEG Project"
description: "Acoustic noise attenuation by vegetation"

# Site URLs (important for GitHub Pages)
url: "https://vukoz-oel.github.io"
baseurl: "/acuveg_database"
destination: docs

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "main"
      pagination: false
      show_prev_next: false

include:
  - _pages
  - assets
  - _includes
